version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: AWSCODEBUILDTEST/stop_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: AWSCODEBUILDTEST/start_container.sh
      timeout: 300
      runas: root
